### ISSUE TITLE
Quarantine Report - Send Now Illegal string offset

### ISSUE THREAD

**Issue by asuweb** [mailwatch/MailWatch#767]
### Issue summary
Multiple `PHP Warning:  Illegal string offset` in logs when running "Send Now" for quarantine report

Reports are not sent either

```
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'timestamp' in /var/www/html/mailscanner/quarantine_report.inc.php on line 600, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'timestamp' in /var/www/html/mailscanner/quarantine_report.inc.php on line 600, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'token' in /var/www/html/mailscanner/quarantine_report.inc.php on line 528, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'id' in /var/www/html/mailscanner/quarantine_report.inc.php on line 528, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'id' in /var/www/html/mailscanner/quarantine_report.inc.php on line 491, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'rand' in /var/www/html/mailscanner/quarantine_report.inc.php on line 533, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'id' in /var/www/html/mailscanner/quarantine_report.inc.php on line 471, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'rand' in /var/www/html/mailscanner/quarantine_report.inc.php on line 472, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'id' in /var/www/html/mailscanner/quarantine_report.inc.php on line 541, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'rand' in /var/www/html/mailscanner/quarantine_report.inc.php on line 541, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'datetime' in /var/www/html/mailscanner/quarantine_report.inc.php on line 548, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'to' in /var/www/html/mailscanner/quarantine_report.inc.php on line 549, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'from' in /var/www/html/mailscanner/quarantine_report.inc.php on line 550, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'subject' in /var/www/html/mailscanner/quarantine_report.inc.php on line 551, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'reason' in /var/www/html/mailscanner/quarantine_report.inc.php on line 552, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'datetime' in /var/www/html/mailscanner/quarantine_report.inc.php on line 558, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'to' in /var/www/html/mailscanner/quarantine_report.inc.php on line 559, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'from' in /var/www/html/mailscanner/quarantine_report.inc.php on line 560, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'subject' in /var/www/html/mailscanner/quarantine_report.inc.php on line 561, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'reason' in /var/www/html/mailscanner/quarantine_report.inc.php on line 562, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'token' in /var/www/html/mailscanner/quarantine_report.inc.php on line 528, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'id' in /var/www/html/mailscanner/quarantine_report.inc.php on line 528, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'id' in /var/www/html/mailscanner/quarantine_report.inc.php on line 491, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'rand' in /var/www/html/mailscanner/quarantine_report.inc.php on line 533, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'id' in /var/www/html/mailscanner/quarantine_report.inc.php on line 471, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'rand' in /var/www/html/mailscanner/quarantine_report.inc.php on line 472, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'id' in /var/www/html/mailscanner/quarantine_report.inc.php on line 541, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'rand' in /var/www/html/mailscanner/quarantine_report.inc.php on line 541, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'datetime' in /var/www/html/mailscanner/quarantine_report.inc.php on line 548, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'to' in /var/www/html/mailscanner/quarantine_report.inc.php on line 549, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'from' in /var/www/html/mailscanner/quarantine_report.inc.php on line 550, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'subject' in /var/www/html/mailscanner/quarantine_report.inc.php on line 551, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'reason' in /var/www/html/mailscanner/quarantine_report.inc.php on line 552, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'datetime' in /var/www/html/mailscanner/quarantine_report.inc.php on line 558, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'to' in /var/www/html/mailscanner/quarantine_report.inc.php on line 559, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'from' in /var/www/html/mailscanner/quarantine_report.inc.php on line 560, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'subject' in /var/www/html/mailscanner/quarantine_report.inc.php on line 561, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
[Fri Apr 28 09:18:26 2017] [error] [client x.x.x.x] PHP Warning:  Illegal string offset 'reason' in /var/www/html/mailscanner/quarantine_report.inc.php on line 562, referer: https://example.com/user_manager.php?token=f75be9be468a7064bd77b85a4d6a5fea882b8775df1b067bbabeb9795667658c&action=edit&key=user@example.com
```
### Steps to reproduce
1. Tail the log file
2. Run "Send Now" for a user

### Expected result
No errors should be logged

Quarantine Report should be sent to user

### Actual result
Multiple Warning in log files
No Quarantine Report Sent to user

### Version and method
 - MailWatch Version: 1.2.3-dev (latest git develop branch)
 - Install type: [ GitHub checkout ]
 - Updated from an older MailWatch or fresh install: [ Upgrade ] (from version [ 1.2.3-dev ])

### Server configuration
 - Operation System: [ CentOS  ]
 - PHP version: [ 5.6 ]
 - Database: [  MariaDB ] version [ 10.1.22-MariaDB ]
 - Mail Server: [ Postfix ]
 - Used web server: [ Apache ]

**Comment by stefaweb** [comment]
Same here but I receive a mail with wrong contents.

![capture d ecran 2017-04-28 a 10 33 47](https://cloud.githubusercontent.com/assets/12907102/25520983/4f7473ce-2bfe-11e7-86b5-66f15e6d2e66.png)

**Comment by asuweb** [comment]
Yes, when I invoke it from the command line, it does send the report email, as per your screenshot.  Seems completely broken currently

**Comment by asuweb** [comment]
The issue is do do with Combined Filters - looking at it just now

**Comment by asuweb** [comment]
It's fixed in the following commit

**Comment by asuweb** [comment]
Fixed in #768

There is still an issue with the links in reports having the `&` converted to `&amp;` when clicked

**Comment by asuweb** [comment]
Merged - closed

**Comment by stefaweb** [comment]
Hello!

Still not solved. The report is now "empty".

![capture d ecran 2017-05-02 a 08 54 29](https://cloud.githubusercontent.com/assets/12907102/25607062/1aab5d82-2f15-11e7-8bb7-ff193df79f79.png)

**Comment by asuweb** [comment]
There is a further bug where the report is sent when there are no quarantined mail for the time period. 

In the text it says 0 quarantined items, so the report shouldn't have been sent

**Comment by asuweb** [comment]
@stefaweb = fixed in #771
